name: Build and Test
on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run: yarn
      - name: storybook
        run: yarn start:storybook &
      - name: creevey
        run: yarn creevey
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: report
      #     path: report/
